package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AsientoVendidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoVendidoAllPropertiesEquals(AsientoVendido expected, AsientoVendido actual) {
        assertAsientoVendidoAutoGeneratedPropertiesEquals(expected, actual);
        assertAsientoVendidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoVendidoAllUpdatablePropertiesEquals(AsientoVendido expected, AsientoVendido actual) {
        assertAsientoVendidoUpdatableFieldsEquals(expected, actual);
        assertAsientoVendidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoVendidoAutoGeneratedPropertiesEquals(AsientoVendido expected, AsientoVendido actual) {
        assertThat(actual)
            .as("Verify AsientoVendido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoVendidoUpdatableFieldsEquals(AsientoVendido expected, AsientoVendido actual) {
        assertThat(actual)
            .as("Verify AsientoVendido relevant properties")
            .satisfies(a -> assertThat(a.getFila()).as("check fila").isEqualTo(expected.getFila()))
            .satisfies(a -> assertThat(a.getColumna()).as("check columna").isEqualTo(expected.getColumna()))
            .satisfies(a -> assertThat(a.getPersona()).as("check persona").isEqualTo(expected.getPersona()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientoVendidoUpdatableRelationshipsEquals(AsientoVendido expected, AsientoVendido actual) {
        assertThat(actual)
            .as("Verify AsientoVendido relationships")
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()));
    }
}
