package com.mycompany.myapp.domain;

import com.mycompany.myapp.evento.infrastructure.persistence.entity.IntegranteEntity;

import static org.assertj.core.api.Assertions.assertThat;

public class IntegranteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegranteAllPropertiesEquals(IntegranteEntity expected, IntegranteEntity actual) {
        assertIntegranteAutoGeneratedPropertiesEquals(expected, actual);
        assertIntegranteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegranteAllUpdatablePropertiesEquals(IntegranteEntity expected, IntegranteEntity actual) {
        assertIntegranteUpdatableFieldsEquals(expected, actual);
        assertIntegranteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegranteAutoGeneratedPropertiesEquals(IntegranteEntity expected, IntegranteEntity actual) {
        assertThat(actual)
            .as("Verify Integrante auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegranteUpdatableFieldsEquals(IntegranteEntity expected, IntegranteEntity actual) {
        assertThat(actual)
            .as("Verify Integrante relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getIdentificacion()).as("check identificacion").isEqualTo(expected.getIdentificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegranteUpdatableRelationshipsEquals(IntegranteEntity expected, IntegranteEntity actual) {
        assertThat(actual)
            .as("Verify Integrante relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
